package com.example.tetragon.questions.questionMathSecondGrade

enum class MathGrade2Type(val xp: Int) {
    ARITHMETICS_BASICS(2),
    ADDITION_INTERACTIVE(2),

    COLUMN_METHOD_ADDITION(2),
    COLUMN_METHOD_ADDITION_MATCH(3),

    COLUMN_METHOD_ADDITION_THREE_DIGITS(3),
    COLUMN_METHOD_SUBTRACTION_THREE_DIGITS(3),

    COMPARISON_THREE_DIGITS(2),
    COMPARISON_THREE_DIGITS_ARITHMETICS(3),

    METER_TO_CM(2),
    MEASUREMENT_ARITHMETICS(3),

    SET_TIME(2),
    TIME_ARITHMETICS(3),

    MULTIPLICATION_TABLE(2),
    MULTIPLICATION_INTERACTIVE(2),

    DIVISION_SIMPLE(2),
    DIVISION_INTERACTIVE(2)
}