package com.tetragon.app.questions.questionMathFirstGrade

enum class MathGrade1Type(val xp: Int) {
    APPLE(1),
    FIND_MISSED_NUMBER(1),
    ANGLES(2),
    FIND_NEXT_NUMBER(1),

    ADDITION_NUMBERS(2),
    ADDITION_MISSED_NUMBER(2),
    ADDITION_TWO_REPRESENTATION(2),
    ADDITION_THREE_REPRESENTATION(3),
    ADDITION_VISUAL_PROBLEM(2),
    ADDITION_TREE(2),
    BASIC_AI_ADDITION(2),

    SUBTRACTION_NUMBERS(2),
    SUBTRACTION_MISSED_NUMBER(2),
    SUBTRACTION_TWO_REPRESENTATION(2),

    UP_TO_EVEN_OR_ODD(3),
    EVEN_OR_ODD(2),
    FIND_EVEN_OR_ODD_SEQUENCE(2),
    CONTINUE_SEQUENCE_ODD_OR_EVEN(1),

    COMPARISON(3),
    COMPARISON_TRUE_OR_FALSE(1),
    COMPARISON_GRAPE_OR_STRAWBERRY(1),

    PARENTHESES(3),
    PARENTHESES_MISSED(3),

    ADDITION_20(1),
    ADDITION_MISSED_NUMBER_20(2),
    ADDITION_THREE_REPRESENTATION_20(2),
    ADDITION_TWO_REPRESENT_20(2),
    ADDITION_VISUAL_PROBLEM_20(2),

    SUBTRACTION_MISSED_NUMBER_20(2),
    SUBTRACTION_TWO_REPRESENTATION_20(2),
    SUBTRACTION_NUMBERS_20(2),

    CONTINUE_SEQUENCE_ROUND_NUMBERS(1),
    ARITHMETICS_ROUND_NUMBERS(2),
    CLOSEST_ROUND_NUMBERS(1),
    HOW_MANY_TENS_ROUND_NUMBERS(2),

    COMPARISON_TWO_DIGITS(2),
    ARITHMETICS_TWO_DIGIT_NUMBERS(3),
    COMPARISON_TRUE_OR_FALSE_TWO_DIGIT_NUMBERS(2),
    ADDITION_TWO_DIGIT_NUMBER_REPRESENTATION(2),
    ARITHMETICS_VISUAL_TWO_DIGIT_NUMBERS_PROBLEM(2),
    PARENTHESES_TWO_DIGIT_NUMBERS(3),
    PARENTHESES_MISSED_TWO_DIGIT_NUMBERS(3),

    FISH(2),
    AZIZ_APPLE_PROBLEM(2),

    CM_RULER(2),
    DM_IN_CM(3),
}